### ISSUE TITLE
Critical integrity vs Ownership integrity is calculated slightly differently than the game does it

### ISSUE THREAD

**Issue by highlyunavailable** [Ash-LikeSnow/ModAdjuster#2]
A more correct way to calculate the ownership integrity for [`SetRatios`](https://github.com/Ash-LikeSnow/ModAdjuster/blob/master/Data/Scripts/Adjuster/script/AdjustSBC.cs#L284) would be as follows, based off of how the game does it, since it uses the first computer if possible and the ratio is 0 if there's no computer. If you want to be exactly accurate to how the game does it, weird numbers and all, `SetRatios` should look like this:

```csharp
var criticalIntegrity = 0f;
var ownershipIntegrity = 0f;
for (var index = 0; index <= criticalIndex; index++)
{
    var component = blockDef.Components[index];
    if (ownershipIntegrity == 0f && component.Definition.Id.SubtypeName == "Computer")
    {
        ownershipIntegrity = criticalIntegrity + component.Definition.MaxIntegrity;
    }
    criticalIntegrity += component.Count * component.Definition.MaxIntegrity;
    if (index == criticalIndex)
    {
        criticalIntegrity -= component.Definition.MaxIntegrity;
    }
}

blockDef.CriticalIntegrityRatio = criticalIntegrity / blockDef.MaxIntegrity;
blockDef.OwnershipIntegrityRatio = ownershipIntegrity / blockDef.MaxIntegrity;

var count = blockDef.BuildProgressModels.Length;
for (var index = 0; index < count; index++)
{
    var buildPercent = (index + 1f) / count;
    blockDef.BuildProgressModels[index].BuildRatioUpperBound = buildPercent * blockDef.CriticalIntegrityRatio;
}
```

That's based off of this code from `MyCubeBlockDefinition.Init(MyObjectBuilder_DefinitionBase builder)`:
![image](https://user-images.githubusercontent.com/6266125/180621714-ae087d14-dbbf-4734-b853-9b326b65c000.png)

**Comment by Ash-LikeSnow** [comment]
I'll take your word for it, if you submit a PR I'll accept :)
