### ISSUE TITLE
ChangeIcon

### ISSUE THREAD

**Issue by ImperatorPortfolio** [Ash-LikeSnow/ModAdjuster#4]
Hey!

This is an amazing Mod, but I can´t seem to get ChangeIcon working.

I know it says you have only recently added this but did you get it working?

I tried it like this just as a test:

namespace ModAdjuster
{
    public class BlockDefinitions
    {
        public static List<BlockDef> BlockDefs = new List<BlockDef>()
        {
			new BlockDef()
            {
                BlockName = "MyObjectBuilder_Cockpit/RoverPassengerSeat",
                BlockActions = new[]
                {
                    // These modifications are specific to ship tools
                    new BlockAction
                    {
                        Action = ChangeIcon, // Set the effect radius of any ship tool (welder, grinder, drill)
                        Value = "Textures\\GUI\\Icons\\Blueprints\\Bp_food.png"
                    }
                }
            },
        };

    }
}

Am I doing something wrong?

Would greatly appreciate any advice

Imperator

**Comment by Ash-LikeSnow** [comment]
Sorry I didn't reply to this, I hope you figured it out, but in case you didn't, it should look like this:
```                    new BlockAction
                    {
                        Action = ChangeIcon,
                        NewText = "\\Textures\\GUI\\Icons\\Cubes\\Fake.dds"
                    }
```
